# Version should be what `git describe --tags` gives you at the `commit`
{% set version = "0.3.0.103.g5496ffc" %}
{% set commit = "5496ffcb4d9d24ee4af2754aafc124c5fc0e21c5" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/symengine/symengine.py/archive/{{ commit }}.tar.gz

build:
  number: 0
  skip: true        # [win and py<35]
  features:
    - vc14          # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - symengine     0.3.0.353.g22cef70
    - python
    - cython
    - setuptools
    - llvmdev       >=3.9
  run:
    - symengine     0.3.0.353.g22cef70
    - python
    - numpy

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine
  commands:
    - python -c $'import symengine;\nif not symengine.test():\n raise Exception("Tests failed")'    # [unix]

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: 'Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
