travis:
  secure:
    BINSTAR_TOKEN: nhNlG1WRFE3UbX6MFBFDtFOtNX0xojzGc+4LwPTT++5bgDUwi2TQGADQ5me0NHZUq2Dg0ggyzzjI1AfF/hT4rINWA5WbgVtOuGpfMcOGo+bUpUaAhj58ENrAjDi2zFFCZOQeRmBi8S0/Zgtr0ocTuMpFEMdUWkBBrQOmnGcwfyp9xUBJfIEJADQDbu6fOn1XBgES51SsXzX2bWUGC5Zp8Zf9fUFpfVDaKWbz8YTiDtDoHgywG7a/vZABrvwZ2znTv1vbG0NSSqwtW8XQ+nekEE1gDcEHwQY8idO8ChPD/24Sw+FIfDOD46b1zvb3T41wz0CyoVbzLXTnGnyYyJJUQNsu+eTqA3MDphZMrfAAD7mh2J6gK+1ue7BzEIuJog2NN1URYheVeZiHmuzjOL5RzY3QyJTebZ5YN3dvX+P7lgLS373i+bB5O/+XsE3OsgqUxclhL3bXT8lFQvy5LBW+KjmlBP+a4n92btw79wuYp+DiBYAypzxC2u7d9OM6DknaZIvxEfUNEXk3B1UWz2h9w/Idxl/Jy8SUSycUAj/XLEILcpqxEMOHy4KbggK7Y/gZCd2SR2UwdCuwmDbZU8YO+7GnhKdwZyYNwvj0v7hhpV4vNWNnSe2bM7jPBPDA0J/CU5y/V91uSn9hcUHy2tHk0fWeMCTBFuUfNqbDSvLwU14=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
