channels:
  sources: [symengine/label/dev, symengine, conda-forge, defaults]
  targets:
    - [symengine, dev]
travis:
  secure:
    BINSTAR_TOKEN: ZoDbLnY2IDuhQRxLtHHiN242R43uSD4CGgxGKI3eBhyJU4zphU+b5nwfbVoK3W3cW9WVp6mKZWlqqbhQdrtJjLvkQLGbWCNSAS7iKZfJ3EwgWM1SM7RYkmNNg4hFPGerAWD7nx/0Hm8gklxt6wcpf7k424DHCSSeSogz3s0XOFkhdjvaWvuytkV5GUcO9y38UQX9891LHO/1SmhjxjBgY/y/38IIK7v2YdJMPmStXN5v7Wha0AxTyXZzKfvAalXRa0gy0L5Hioxz4Nbnv20GoOB5vOhdD7uNx9zW8PaYNGq1KaTwvcQknXIEI1X79+JJUc4T7HKwfJ905TEz0LEEwjtqeelwqACI4JynA5cyE7yze6pdvxgUTr+DVx0UIkUrOPiha1rYZmj3X7rDlNP6WeCoEjvpfyKmnc24tcYxNlxzf9G5PJNSj1dLlkDM+b+Y2VP/evQ/z1kbFzCeKpZFRDOZVYO6Q5/hu/Lc/UWPKfFOO+QMH0VVqDveeE62IQY1xF+wHra/lL5zi8rj0xsKmrCxxAdS0HNiMT03vDp13H9fL9+Jjn3GpXcklh367LUG61czRN0TlGXK4mkY9B9JlnumCe5mI0Jdo4IUqYnNSBw85eKU3cYyPk0sPs5N77pfZEVCJolg6RpXhdaM/cheCnCcrXVQ50RVUCOYmADNewY=
appveyor:
  secure:
    BINSTAR_TOKEN: mnyKh9WUccsl/wEyLwP/ImhWItQ7cBiukFPSLwd52px18jRYq4SyL/ETYediXrUu
